{
    "NOMBRE_PROYECTO": "$NOMBRE_PROYECTO",
    "DESCRIPCION_PROYECTO": "$DESCRIPCION_PROYECTO",
    "DESCRIPCION_DETALLADA": "$DESCRIPCION_DETALLADA",
    "OBJETIVO_PROYECTO": "{{OBJETIVO_PROYECTO}}",
    "FUNCIONALIDAD_PRINCIPAL": "{{FUNCIONALIDAD_PRINCIPAL}}",
    "TIPO_PROYECTO": "TD_MCP Project",
    "AUTOR": "$AUTOR",
    "EMAIL_CONTACTO": "$EMAIL_CONTACTO",
    "GITHUB_USER": "$GITHUB_USER",
    "REPOSITORIO_URL": "{{REPOSITORIO_URL}}",
    "PYTHON_VERSION_MIN": "$PYTHON_VERSION_MIN",
    "LICENCIA": "$LICENCIA",
    "FECHA_CREACION": "{{FECHA_CREACION}}",
    "FECHA_ACTUALIZACION": "{{FECHA_ACTUALIZACION}}",
    "MODULO_PRINCIPAL": "$MODULO_PRINCIPAL",
    "CLASE_PRINCIPAL": "$CLASE_PRINCIPAL",
    "ESTADO_INICIAL": "Fase inicial - Configuración TD_MCP",
    "PRIMER_PASO": "Configurar TouchEngine SDK",
    "SEGUNDO_PASO": "Implementar conexión básica con TouchDesigner",
    "TERCER_PASO": "Crear herramientas MCP básicas",
    "SIGUIENTE_PASO": "Probar integración con TouchDesigner",
    "EJEMPLO_USO": "# Crear servidor MCP\nserver = $CLASE_PRINCIPAL()\n# Conectar con TouchDesigner\nawait server._connect()\n# Cargar archivo .tox\nawait server._load_tox('proyecto.tox')",
    "CONFIGURACION_EJEMPLO": "# Configuración para $NOMBRE_PROYECTO\nMCP_SERVER_PORT = 8000\nTOUCHDESIGNER_PORT = 8080\nDEBUG = True",
    "DEPENDENCIAS_PRINCIPALES": "psutil>=5.9.0\nwebsockets>=11.0.0\npydantic>=2.0.0\nasyncio-mqtt>=0.13.0",
    "DEPENDENCIAS_DESARROLLO": "pytest>=7.0.0\npytest-cov>=4.0.0\nblack>=22.0.0\nflake8>=5.0.0",
    "DEPENDENCIAS_TESTING": "pytest>=7.0.0\npytest-cov>=4.0.0\npytest-asyncio>=0.21.0",
    "DEPENDENCIAS_OPCIONALES": "# Dependencias opcionales\n# requests>=2.28.0\n# numpy>=1.21.0\n# matplotlib>=3.5.0",
    "PALABRAS_CLAVE": "touchdesigner, mcp, middleware, python, real-time",
    "NODE_VERSION": "18.0.0"
}
